### ISSUE TITLE
Implement debug state in new edit form

### ISSUE THREAD

**Issue by iJungleboy** [2sic/eav-ui#69]
## I'm submitting a ...
[x] action / task

## ...about
[x] edit experience / UI

## Task / Action Summary
The form should have an advanced debug mode for developers needing to override certain settings. In this mode you can override certain restrictions or add values which are usually not allowed. You can also view invisible fields which are usually hidden. 

### Entering Debug Mode

1. Either by pressing ctrl+alt+shift and clicking on the header
1. or because debug=true is in the url

_note that ctrl+alt+shift+click would toggle debug off again_

### Visualization of debug mode

1. Upon entering, a toaster message should appear saying "debug mode enabled"
1. ideally it would also appear when the page loads in debug mode, but it's not required if this takes more than like 10 mins to implement
1. The bottom of the form should be extended to include a footer-bar of buttons which are only available in debug mode. This bar should look normal (no special colors) and be similar in size as the header bar 
1. On the bar we will show various buttons relevant for debug

### Button in the debug-bar on the edit form

1. Show data - this should show the entity-data in the format it would be saved in with everything, so a developer can see field names and what's really in the data. Please visualize in a similar way like the old form (there you needed ctrl+click anywhere in the form to enter debug)

As of now, that's the only button.

### Further Effects of Debug Mode

1. Hidden fields should become visible
1. Fields may show additional features - for example, dropdown-entity should have a new button for adding null-items to the list

## Steps to implement

* [x] Create a global debug state (probably in the store) or in an observable, and make sure it's initialized from the url
* [x] Create the ctrl+alt+shift-Click capture to change the state
* [x] create a subscription which listens to the observable and shows the toaster
* [x] change form to optionally add the footer with the button
* [x] add the button and the debug display of the data
* [ ] change the form so hidden fields are visible if debug is true (but would go away again if debug is off again)

This is related to https://github.com/2sic/2sxc/issues/1680
